task:
  name: macos_arm64
  alias: macos_arm64
  trigger_type: manual
  timeout_in: 90m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  brew_script:
    - brew update
    - brew install ghc@9.6 cabal-install
  env:
    PATH: /opt/homebrew/opt/ghc@9.6/bin:${PATH}
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: macos_2023_03_12
  deps_script:
    - cabal update
    - cabal build all -fembed_data_files -fserver -flua --dependencies-only
  upload_caches:
    - cabal_store
  install_script:
    - sh macos/make_macos_release.sh
  macos_arm64_artifacts:
    path: ./macos-arm64/**

task:
  name: linux_arm64
  alias: linux_arm64
  trigger_type: manual
  timeout_in: 90m
  arm_container:
    image: quay.io/benz0li/ghc-musl:9.6
    cpu: 4
    memory: 12G
  env:
    CABALOPTS: -f-export-dynamic -fembed_data_files -fserver -flua --enable-executable-static -j4
    GHCOPTS: -j4 +RTS -A256m -RTS -split-sections -optc-Os -optl=-pthread
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: linux_arm64_2023_03_11
  deps_script:
    - cabal update
    - cabal build --dependencies-only $CABALOPTS --ghc-options="$GHCOPTS" pandoc-cli
  upload_caches:
    - cabal_store
  package_script:
    - cabal freeze && cat cabal.project.freeze
    - bash linux/make_artifacts.sh
  linux_arm64_artifacts:
    path: ./linux-arm64/**

task:
  name: linux_amd64
  alias: linux_amd64
  trigger_type: manual
  timeout_in: 90m
  container:
    image: quay.io/benz0li/ghc-musl:9.6
    cpu: 4
    memory: 12G
  env:
    CABALOPTS: -f-export-dynamic -fembed_data_files -fserver -flua --enable-executable-static -j4
    GHCOPTS: -j4 +RTS -A256m -RTS -split-sections -optc-Os -optl=-pthread
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: linux_amd64_2023_03_12
  deps_script:
    - cabal update
    - cabal build --dependencies-only $CABALOPTS --ghc-options="$GHCOPTS" pandoc-cli
  upload_caches:
    - cabal_store
  package_script:
    - cabal freeze && cat cabal.project.freeze
    - bash linux/make_artifacts.sh
  linux_amd64_artifacts:
    path: ./linux-amd64/**

task:
  name: windows_arm64
  alias: windows_arm64
  trigger_type: manual
  timeout_in: 90m
  windows_container:
    image: cirrusci/windowsservercore:2019
    cpu: 4
    memory: 12G
  os: windows
  cpu: arm64
  env:
    CIRRUS_SHELL: powershell
  windows_task:
    install_script:
      - Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      - .cirrus/build_pandoc_package.ps1
  windows_arm64_artifacts:
    path: ./window_arm64/*

